# Generated by Django 4.0 on 2022-04-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exercise', '0002_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='addressable_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
