# Generated by Django 4.0 on 2022-04-13 07:20

from django.db import migrations
# with open(master_data/tokyo.csv) as f:
#         reader = csv.reader(f)
#         for row in reader:
#             _, created = Teacher.objects.get_or_create(
#                 first_name=row[0],
#                 last_name=row[1],
#                 middle_name=row[2],
#                 )
def random_address(apps, schema_editor):
    Address=apps.get_model('exercise','Address')
    for i in range(5):
        Address.objects.create(
            line1=f"Line 1 example {i}",
            line2=f"lin2 example{i}",
            line3=f"lin3 example{i}",
            prefecture=f"prefecture example {i}",
            city=f"City example{i}",
            postalcode=f"postalcode example {i}"
            )

def setup_shop(apps, schema_editor):
    Shop=apps.get_model('exercise','Shop')
    for i in range(5):
        Shop.objects.create(name=f"Shop name {i}")

    for shop in Shop.objects.all():
        shop.foods.create(name=f"Food name {shop.id}",price=200,type=f"Food type {shop.id}")

def setup_customer(apps, schema_editor):
    Customer=apps.get_model('exercise','Customer')
    Address=apps.get_model('exercise','Address')
    for i in range(5):
        Customer.objects.create(name=f"Customer name {i}")

    for customer in Customer.objects.all():
        customer.orders.create(address=Address.objects.first())

class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_address_addressable_id_address_content_type'),
    ]

    operations = [
        migrations.RunPython(random_address),
        migrations.RunPython(setup_shop),
        migrations.RunPython(setup_customer)
    ]
